---
- hosts: backup_client
  tasks:
  - block:
    - name: Borg client is installed
      become: true
      ansible.builtin.package:
        name: borgbackup
        state: latest

    - name: Check if SSH keypair already exists in the local /keys directory
      ansible.builtin.stat: # Read filename properties
        path: "keys/{{ backup_volume }}" # Find files in /keys where the filename matches the volume_backup label given in inventory.yml
      delegate_to: localhost # Run on the local machine
      register: keypair # Store in a variable

    - name: Generate SSH keypair for each backup_volume defined in inventory.yml
      community.crypto.openssh_keypair:
        type: rsa
        path: "keys/{{ backup_volume }}"
      delegate_to: localhost # Run on the local machine
      when: not keypair.stat.exists # Only generate a new keypair if one doesn't already exist

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory

    - name: Copy private key to backup client
      ansible.builtin.copy:
        src: "keys/{{ backup_volume }}"
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa" # And rename them to their default name

    - name: Copy public key to backup client
      ansible.builtin.copy:
        src: "keys/{{ backup_volume }}.pub"
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"

    - name: Check if id_rsa file is present
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.ssh/id_rsa"
      register: result

    - name: Set restrictive permissions on private key
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh/id_rsa"
        mode: '0600'
