---
- hosts: all
  gather_facts: no
  tasks:
    - block:
        - name: Add hosts of backup_server into known hosts file
          known_hosts:
            name: "{{ hostvars[item].ansible_host }}"
            key: "{{ lookup('pipe', 'ssh-keyscan ' + hostvars[item].ansible_host) }}"
          when: hostvars[item].backup_volume is defined and hostvars[item].backup_volume != ''
            
          with_items: "{{ groups['backup_server'] }}"

        - name: Print the command that will be run
          debug:
            msg: "borg init --encryption=none backup@{{ hostvars[backup_server].ansible_host }}:{{ hostvars[inventory_hostname].backup_volume }}"
          when: hostvars[inventory_hostname].backup_volume is defined and hostvars[inventory_hostname].backup_volume != ''
          loop: "{{ groups['backup_server'] }}"
          loop_control:
            loop_var: backup_server

        - name: Initialize a corresponding Borg repository on each client
          command:
            cmd: "borg init --encryption=none backup@{{ hostvars[backup_server].ansible_host }}:{{ hostvars[inventory_hostname].backup_volume }}"
          when: hostvars[inventory_hostname].backup_volume is defined and hostvars[inventory_hostname].backup_volume != ''
          loop: "{{ groups['backup_server'] }}" # Loop through all backup servers
          loop_control:
            loop_var: backup_server
