---
- hosts: all
  tasks:
  - name: Borg client is installed on all machines with backup volumes
    become: true
    ansible.builtin.package:
      name: borgbackup
      state: latest
    when: backup_volume is defined and backup_volume != ''
    
  - name: Generate SSH keys locally
    when: backup_volume is defined
    block:
      - name: Generate SSH keypair for {{ backup_volume }}
        community.crypto.openssh_keypair:
          type: rsa
          path: "keys/{{ backup_volume }}"
        delegate_to: localhost

      - name: Copy private key to appropriate remote machine
        ansible.builtin.copy:
          src: "keys/{{ backup_volume }}"
          dest: "/home/{{ ansible_user }}/.ssh/"
        delegate_to: "{{ inventory_hostname }}"