---
- name: Deploy Minecraft Docker Compose
  hosts: blade
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check

    - name: Install Docker if not installed
      include_tasks: install-docker.yml
      when: docker_check.rc != 0
  
    - name: Copy docker-compose.yml file
      copy:
        src: compose/minecraft-server.yml
        dest: "{{ ansible_env.HOME }}/minecraft-server/docker-compose.yml"

    - name: Run docker-compose
      command: docker-compose up -d --remove-orphans
      args:
        chdir: "{{ ansible_env.HOME }}/minecraft-server"
