---
- hosts: all
  become: true
  tasks:
  - name: Make sure the current version of borgbackup is installed.
    ansible.builtin.package:
      name: borgbackup
      state: latest

  - name: Generate SSH key pair
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_rsa
      size: 2048

  - name: Fetch hostname of target machine
    ansible.builtin.setup:
      filter: ansible_hostname

  - name: Fetch public key to local machine
    ansible.builtin.fetch:
      src: ~/.ssh/id_rsa.pub
      dest: "pubkeys/{{ ansible_hostname }}.pub"
      flat: yes