---
- name: Deploy caddy Docker Compose
  hosts: caddy
  become: true
  tasks:
    - name: Set timezone to Stockholm # Change to your own timezone
      ansible.builtin.timezone:
        name: "Europe/Stockholm"

    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check

    - name: Install Docker if not installed
      include_tasks: install-docker.yml
      when: docker_check.rc != 0

    - name: Ensure pocketbase directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/caddy"
        state: directory