---
- hosts: myhosts
  become: true

  roles:
    - role: geerlingguy.docker
      vars:
        docker_edition: "ce"
        docker_packages_state: latest
        docker_service_manage: true
        docker_service_state: started
        docker_service_enabled: true
        docker_restart_handler_state: restarted
    - role: geerlingguy.pip