---
- hosts: all
  tasks:
  - block:
    - name: Borg client is installed on all machines with backup volumes
      become: true
      ansible.builtin.package:
        name: borgbackup
        state: latest

    - name: Check if SSH keypair already exists
      ansible.builtin.stat:
        path: "keys/{{ backup_volume }}"
      delegate_to: localhost
      register: keypair

    - name: Generate SSH keypair for {{ backup_volume }}
      community.crypto.openssh_keypair:
        type: rsa
        path: "keys/{{ backup_volume }}"
      delegate_to: localhost
      when: not keypair.stat.exists

    - name: Copy private key to appropriate remote machine
      ansible.builtin.copy:
        src: "keys/{{ backup_volume }}"
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa" # and rename them to their default name
      delegate_to: "{{ inventory_hostname }}"

    - name: Set restrictive permissions on private key
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh/id_rsa"
        mode: '0600'
      delegate_to: "{{ inventory_hostname }}"

    when: backup_volume is defined and backup_volume != ''