---
- name: Deploy pihole Docker Compose
  hosts: pihole_server
  become: true
  tasks:
    - name: Set timezone to Stockholm # Change to your own timezone
      ansible.builtin.timezone:
        name: "Europe/Stockholm"

    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check

    - name: Install Docker if not installed
      include_tasks: install-docker.yml
      when: docker_check.rc != 0

    - name: Ensure pihole directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/pihole"
        state: directory

    - name: Disable and stop systemd-resolved, set nameserver (Ubuntu only)
      block:
        - name: Disable systemd-resolved
          ansible.builtin.systemd:
            name: systemd-resolved
            enabled: no

        - name: Stop systemd-resolved
          ansible.builtin.systemd:
            name: systemd-resolved
            state: stopped
      when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"

    - name: Copy docker-compose.yml to remote
      ansible.builtin.copy:
        src: ../compose/pihole.yml
        dest: "/home/{{ ansible_user }}/pihole/docker-compose.yml"

    - name: Run docker-compose
      command: docker compose up -d --remove-orphans
      args:
        chdir: "/home/{{ ansible_user }}/pihole"
