version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy    
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - config:/config

volumes:
  caddy_data:
    external: true
  config: