version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.    
     - GF_AUTH_ANONYMOUS_ORG_ROLE=admin
     - GF_AUTH_ORG_ROLE=admin
     - GF_AUTH_BASIC_ENABLED=false
     - GF_AUTH_DISABLE_LOGIN_FORM=true
     - GF_AUTH_DISABLE_SIGNOUT_MENU=true
    ports:
     - '3000:3000'
    volumes:
      - data:/var/lib/grafana
      

volumes:
  data: