services:
  minecraft:
    image: phyremaster/papermc:latest
    container_name: minecraft
    ports:
      - "25565:25565"
      - "25575:25575"
#     - "8080:8080" # Uncomment this line to enable plugins with web front-ends such as Dynmap
      - "19132:19132/udp"
    volumes:
      - data:/papermc
    environment:
      - EULA=true
      - MC_RAM=12G
      - MC_VERSION=latest
      - TZ="Europe/Berlin"
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  data: