version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "2000:2000/tcp"
    environment:
      TZ: 'Sweden/Stockholm'
      WEBPASSWORD: '1234' # Good enough as long as you don't expose the port to the internet
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped