services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional
    ports:
      - "8090:80"
    volumes:
      - pocketbase:/pb_data
      - pocketbase:/pb_public

volumes:
  pocketbase:
    name: "pocketbase"