---
- name: Deploy Minecraft Docker Compose
  hosts: minecraft_server
  become: true
  tasks:
    - name: Set timezone to Stockholm # Change to your own timezone
      ansible.builtin.timezone:
        name: "Europe/Stockholm"

    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check

    - name: Install Docker if not installed
      include_tasks: install-docker.yml
      when: docker_check.rc != 0

    - name: Ensure minecraft directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/minecraft"
        state: directory

    - name: Copy docker-compose.yml to remote
      ansible.builtin.copy:
        src: ../compose/minecraft-server.yml
        dest: "/home/{{ ansible_user }}/minecraft/docker-compose.yml"

    - name: Check if rconclt is installed # Minecraft needs to execute /save-all before starting a backup
      command: rconclt -h
      ignore_errors: true
      register: rcon_check

    - name: Install rcon if not installed
      include_tasks: install-rcon.yml
      when: rcon_check.rc != 0

    - name: Run docker-compose
      command: docker compose up -d --remove-orphans
      args:
        chdir: "/home/{{ ansible_user }}/minecraft"
