- hosts: minecraft_server
  become: true
  vars:
    backup_volume: "{{ hostvars[inventory_hostname]['backup_volume'] }}"

  tasks:
    - name: Check if minecraft directory exists
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/minecraft"
      register: mcdir_check

    - name: Install the minecraft server if it doesn't exist
      include_tasks: install_minecraft_server.yml
      when: not mcdir_check.stat.exists
  
    - name: Copy minecraft_backup.sh to remote
      copy:
        src: minecraft_backup.sh
        dest: /home/{{ ansible_user }}/minecraft/minecraft_backup.sh
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Ensure log directory exists
      file:
        path: "/home/{{ ansible_user }}/minecraft/logs"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        

    - name: Remove stale borg create commands from minecraft_backup.sh
      lineinfile:
        path: "/home/{{ ansible_user }}/minecraft/minecraft_backup.sh"
        regexp: ".*borg create.*"
        state: absent

    - name: Remove stale borg prune commands from minecraft_backup.sh
      lineinfile:
        path: "/home/{{ ansible_user }}/minecraft/minecraft_backup.sh"
        regexp: ".*borg prune.*"
        state: absent

    - name: Remove stale borg compact commands from minecraft_backup.sh
      lineinfile:
        path: "/home/{{ ansible_user }}/minecraft/minecraft_backup.sh"
        regexp: ".*borg compact.*"
        state: absent

    - name: Insert new borg create commands in minecraft_backup.sh # to backup to all backup servers
      blockinfile:
        path: "/home/{{ ansible_user }}/minecraft/minecraft_backup.sh"
        block: |
          {% for item in groups['backup_server'] %}
          borg create backup@{{ hostvars[item]['ansible_host'] }}:{{ backup_volume }}::mc_${timestamp} "${mcserver_backup_dir}" --list --stats >> /home/{{ ansible_user }}/minecraft/logs/${timestamp}_{{ hostvars[item]['ansible_host'] }}.log 2>&1
          create_exit=$?
          borg prune --glob-archives 'mc_*' --list --show-rc --keep-minutely 24 --keep-daily 14 --keep-weekly 8 --keep-monthly 12 --keep-yearly -1 backup@{{ hostvars[item]['ansible_host'] }}:{{ backup_volume }} >> /home/{{ ansible_user }}/minecraft/logs/${timestamp}_{{ hostvars[item]['ansible_host'] }}.log 2>&1
          prune_exit=$?
          borg compact backup@{{ hostvars[item]['ansible_host'] }}:{{ backup_volume }} >> /home/{{ ansible_user }}/minecraft/logs/${timestamp}_{{ hostvars[item]['ansible_host'] }}.log 2>&1
          compact_exit=$?
          {% endfor %}
        marker: "# {mark}"
        create: yes
        insertafter: '#BORGCREATE' # This is how we know where to insert the borg commands. Needs to be present in the minecraft_backup.sh file

    - name: Set up cron job to run minecraft_backup.sh every 15 minutes, but not between 23:00 PM and 08:00 AM
      ansible.builtin.cron:
        name: "Run minecraft_backup.sh every 15 minutes, but not between 23:00 PM and 08:00 AM"
        user: "{{ ansible_user }}"
        minute: "*/15"
        hour: "8-22"
        job: "/home/{{ ansible_user }}/minecraft/minecraft_backup.sh"